environment:
  matrix:
  - nodejs_version: 0.12
  - nodejs_version: 4
  - nodejs_version: 6

  GCLOUD_TESTS_KEY: key.appveyor.json
  GCLOUD_TESTS_KEY_SECRET:
    secure: usGkvXjqCzDNIQHx8oEncrZOmez7GBocB1EXM+g/9rw=

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: >-
      if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) {
        nuget install secure-file -ExcludeVersion
        secure-file\tools\secure-file -decrypt key.appveyor.json.enc -secret $env:GCLOUD_TESTS_KEY_SECRET
        $env:GCLOUD_TESTS_KEY=$env:APPVEYOR_BUILD_FOLDER + '\' + $env:GCLOUD_TESTS_KEY
      }
  - npm install -g npm # Force using the latest npm to get dedupe during install
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --ignore-scripts

test_script:
  - node --version
  - npm --version
  - npm run lint
  - node ./scripts/build.js

build: off

matrix:
  fast_finish: true
